server:
  port: 8086

security:
  oauth2:
    client:
      client-id: ben1
      client-secret: 123456
      user-authorization-uri: http://localhost:8080/pjb/oauth/authorize
      access-token-uri: http://localhost:8080/pjb/oauth/token
      #认证成功后跳转的url,若是不填写的话,那就是事先访问的url认证后跳转到原访问的URL
      registered-redirect-uri:
    resource:
      jwt:
        key-uri: http://localhost:8080/pjb/oauth/token_key
